// Fix for lib/core/theme/f1_teams.dart
import 'package:flutter/material.dart';

enum F1Team {
  redBull,
  ferrari,
  mercedes,
  mcLaren,
  astonMartin,
  alpine,
  williams,
  alphaTauri,
  alfaRomeo,
  haas,
}

class F1TeamData {
  final String name;
  final String logo;
  final Color primaryColor;
  final Color secondaryColor;
  final Color accentColor;

  const F1TeamData({
    required this.name,
    required this.logo,
    required this.primaryColor,
    required this.secondaryColor,
    required this.accentColor,
  });
}

class F1Teams {
  static const Map<F1Team, F1TeamData> teams = {
    F1Team.redBull: F1TeamData(
      name: 'Red Bull Racing',
      logo: '🏁',
      primaryColor: Color(0xFF1E41FF),
      secondaryColor: Color(0xFFFFB800),
      accentColor: Color(0xFFFFFFFF),
    ),
    F1Team.ferrari: F1TeamData(
      name: 'Scuderia Ferrari',
      logo: '🐎',
      primaryColor: Color(0xFFDC143C),
      secondaryColor: Color(0xFFFFFF00),
      accentColor: Color(0xFF000000),
    ),
    F1Team.mercedes: F1TeamData(
      name: 'Mercedes-AMG',
      logo: '⭐',
      primaryColor: Color(0xFF00D2BE),
      secondaryColor: Color(0xFFC4C4C4),
      accentColor: Color(0xFF000000),
    ),
    F1Team.mcLaren: F1TeamData(
      name: 'McLaren F1',
      logo: '🧡',
      primaryColor: Color(0xFFFF8700),
      secondaryColor: Color(0xFF47C7FC),
      accentColor: Color(0xFFFFFFFF),
    ),
    F1Team.astonMartin: F1TeamData(
      name: 'Aston Martin',
      logo: '💚',
      primaryColor: Color(0xFF006F62),
      secondaryColor: Color(0xFFCEDB00),
      accentColor: Color(0xFFFFFFFF),
    ),
    F1Team.alpine: F1TeamData(
      name: 'Alpine F1',
      logo: '🔵',
      primaryColor: Color(0xFF0090FF),
      secondaryColor: Color(0xFFFF1F5A),
      accentColor: Color(0xFFFFFFFF),
    ),
    F1Team.williams: F1TeamData(
      name: 'Williams Racing',
      logo: '🔷',
      primaryColor: Color(0xFF005AFF),
      secondaryColor: Color(0xFFFFFFFF),
      accentColor: Color(0xFF000000),
    ),
    F1Team.alphaTauri: F1TeamData(
      name: 'AlphaTauri',
      logo: '⚪',
      primaryColor: Color(0xFF2B4562),
      secondaryColor: Color(0xFFFFFFFF),
      accentColor: Color(0xFF000000),
    ),
    F1Team.alfaRomeo: F1TeamData(
      name: 'Alfa Romeo',
      logo: '🔴',
      primaryColor: Color(0xFF900000),
      secondaryColor: Color(0xFFFFFFFF),
      accentColor: Color(0xFF000000),
    ),
    F1Team.haas: F1TeamData(
      name: 'Haas F1',
      logo: '⚫',
      primaryColor: Color(0xFF000000),
      secondaryColor: Color(0xFFFF0000),
      accentColor: Color(0xFFFFFFFF),
    ),
  };

  static F1TeamData getTeamData(F1Team team) {
    return teams[team]!;
  }
}